name: Build and Deploy to Production Branch

on:
  push:
    branches:
      - final

# Sets permissions of the GITHUB_TOKEN to allow pushing to the repository
permissions:
  contents: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: SPA Redirect Hack for GitHub Pages
        run: cp dist/index.html dist/404.html

      - name: Deploy build to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean: true
